#include "CinderPlugin/Interface.h"
#include "CinderPlugin/PluginManager.h"
#include "CinderPlugin/Context.h"
#include "CinderPlugin/types/EmptyPluginBase.h"
#include "CinderPlugin/types/NamedPluginBase.h"
